### ISSUE TITLE
NPM version unzipping fails during install but latest Git master version uzipping works

### ISSUE THREAD

**Issue by TomasHubelbauer** [talmobi/chromium-all-codecs-bin#2]
Hi! Thanks for this, this project is exactly what I need, however I am facing an issue during NPM install. The Chromium ZIP gets installed correctly, but the ZIP then fails to unpack:

```
Error: end of central directory record signature not found
```

I am installing on a Windows 10 64bit machine and am downloading Chromium r706915.

I cloned the repo and tried to run `npm install` in it and that worked.

**Comment by TomasHubelbauer** [comment]
I solved this by running `npm i https://github.com/talmobi/chromium-all-codecs-bin` directly. I think by pushing the latest version to NPM you will fix this for NPM users.

**Comment by talmobi** [comment]
Ah, yes. Thank you.
